### ISSUE TITLE
extra lookups don`t work

### ISSUE THREAD

**Issue by MazokuMaxy** [jimfunk/django-postgresql-netfields#113]
Django 3.2.7
Python 3.9.5

```
class Network(models.Model):
    cidr = CidrAddressField(db_index=True, verbose_name=_('cidr'), help_text=_('network cidr'))
    objects = NetManager()


```
python3 manage.py shell
```
>>> from netw.models import Network
>>> Network.objects.filter(cidr__startswith='10.58')
<QuerySet [<Network: Loopback*, 10.58.0.1/32>, <Network: Loopback*, 10.58.0.2/32>, <Network: Loopback*, 10.58.0.3/32>, <Network: Managment*, 10.58.8.0/22>, <Network: SCUD*, 10.58.12.0/22>, <Network: Printers*, 10.58.16.0/22>, <Network: Phones*, 10.58.20.0/22>, <Network: VideoCam*, 10.58.24.0/22>, <Network: Terminals*, 10.58.28.0/22>, <Network: Workers*, 10.58.32.0/22>, <Network: Workers2*, 10.58.36.0/22>, <Network: Install*, 10.58.40.0/22>, <Network: OpenPoint*, 10.58.44.0/22>]>
>>> Network.objects.filter(cidr__net_contained='10.58.0.0/16')
Traceback (most recent call last):
  File "/usr/lib/python3.9/code.py", line 90, in runcode
    exec(code, self.locals)
  File "<console>", line 1, in <module>
  File "/home/maxy/.local/lib/python3.9/site-packages/netfields/managers.py", line 19, in filter
    return super(NetManager, self).filter(*args, **kwargs)
  File "/home/maxy/.local/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/maxy/.local/lib/python3.9/site-packages/django/db/models/query.py", line 941, in filter
    return self._filter_or_exclude(False, args, kwargs)
  File "/home/maxy/.local/lib/python3.9/site-packages/django/db/models/query.py", line 961, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "/home/maxy/.local/lib/python3.9/site-packages/django/db/models/query.py", line 968, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "/home/maxy/.local/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1393, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/home/maxy/.local/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1412, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "/home/maxy/.local/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1347, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "/home/maxy/.local/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1187, in build_lookup
    lhs = self.try_transform(lhs, lookup_name)
  File "/home/maxy/.local/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1226, in try_transform
    raise FieldError(
django.core.exceptions.FieldError: Unsupported lookup 'net_contained' for CidrAddressField or join on the field not permitted, perhaps you meant contains or icontains?


```

**Comment by jimfunk** [comment]
I can't reproduce this in my environment with Django 3.2.7 on Python 3.8.12:

```
class CidrTestModel(Model):
    field = CidrAddressField()
    objects = NetManager()
```

```
>>> CidrTestModel.objects.filter(field__net_contained="192.0.0.0/8")
<QuerySet [<CidrTestModel: CidrTestModel object (2)>]>
```

There is already a test for this specific operation and it's apparently working for all combinations of Django and Python we test for. Are you able to replicate with a test in tox?

**Comment by MazokuMaxy** [comment]
Sorry, the problem was on my side.
It seems netfields app was excluded from django apps and I did not notice that because everything except lookups was working.

**Comment by jimfunk** [comment]
Glad to see you figured it out
