### ISSUE TITLE
Trying to save a model with a CidrAddressField from Django Admin failes

### ISSUE THREAD

**Issue by micahhausler** [jimfunk/django-postgresql-netfields#28]
I was trying to save a model in Django Admin, and it failed saying

```
TypeError: unexpected type <type 'list'> for addr arg
```
## Model

```
class IpRule(models.Model):
    description = models.CharField(max_length=255)
    active = models.BooleanField(default=True)
    port = models.IntegerField(default=22)
    cidr_ip = CidrAddressField()
```
## Stacktrace

```
Traceback (most recent call last):
  File "/Users/micahhausler/code/secret-project/venv/lib/python2.7/site-packages/django/contrib/staticfiles/handlers.py", line 67, in __call__
    return self.application(environ, start_response)
  File "/Users/micahhausler/code/secret-project/venv/lib/python2.7/site-packages/ambition_messenger/server/django_runserver.py", line 88, in application
    return _django_app(environ, start_response)
  File "/Users/micahhausler/code/secret-project/venv/lib/python2.7/site-packages/django/core/handlers/wsgi.py", line 206, in __call__
    response = self.get_response(request)
  File "/Users/micahhausler/code/secret-project/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 194, in get_response
    response = self.handle_uncaught_exception(request, resolver, sys.exc_info())
  File "/Users/micahhausler/code/secret-project/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 229, in handle_uncaught_exception
    return debug.technical_500_response(request, *exc_info)
  File "/Users/micahhausler/code/secret-project/venv/lib/python2.7/site-packages/django_extensions/management/technical_response.py", line 5, in null_technical_500_response
    six.reraise(exc_type, exc_value, tb)
  File "/Users/micahhausler/code/secret-project/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/micahhausler/code/secret-project/venv/lib/python2.7/site-packages/django/contrib/admin/options.py", line 465, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/Users/micahhausler/code/secret-project/venv/lib/python2.7/site-packages/django/utils/decorators.py", line 99, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/Users/micahhausler/code/secret-project/venv/lib/python2.7/site-packages/django/views/decorators/cache.py", line 52, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/Users/micahhausler/code/secret-project/venv/lib/python2.7/site-packages/django/contrib/admin/sites.py", line 198, in inner
    return view(request, *args, **kwargs)
  File "/Users/micahhausler/code/secret-project/venv/lib/python2.7/site-packages/django/utils/decorators.py", line 29, in _wrapper
    return bound_func(*args, **kwargs)
  File "/Users/micahhausler/code/secret-project/venv/lib/python2.7/site-packages/django/utils/decorators.py", line 99, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/Users/micahhausler/code/secret-project/venv/lib/python2.7/site-packages/django/utils/decorators.py", line 25, in bound_func
    return func(self, *args2, **kwargs2)
  File "/Users/micahhausler/code/secret-project/venv/lib/python2.7/site-packages/django/db/transaction.py", line 371, in inner
    return func(*args, **kwargs)
  File "/Users/micahhausler/code/secret-project/venv/lib/python2.7/site-packages/django/contrib/admin/options.py", line 1244, in change_view
    if form.is_valid():
  File "/Users/micahhausler/code/secret-project/venv/lib/python2.7/site-packages/django/forms/forms.py", line 129, in is_valid
    return self.is_bound and not bool(self.errors)
  File "/Users/micahhausler/code/secret-project/venv/lib/python2.7/site-packages/django/forms/forms.py", line 121, in errors
    self.full_clean()
  File "/Users/micahhausler/code/secret-project/venv/lib/python2.7/site-packages/django/forms/forms.py", line 275, in full_clean
    self._post_clean()
  File "/Users/micahhausler/code/secret-project/venv/lib/python2.7/site-packages/django/forms/models.py", line 419, in _post_clean
    self.validate_unique()
  File "/Users/micahhausler/code/secret-project/venv/lib/python2.7/site-packages/django/forms/models.py", line 428, in validate_unique
    self.instance.validate_unique(exclude=exclude)
  File "/Users/micahhausler/code/secret-project/venv/lib/python2.7/site-packages/django/db/models/base.py", line 754, in validate_unique
    errors = self._perform_unique_checks(unique_checks)
  File "/Users/micahhausler/code/secret-project/venv/lib/python2.7/site-packages/django/db/models/base.py", line 838, in _perform_unique_checks
    qs = model_class._default_manager.filter(**lookup_kwargs)
  File "/Users/micahhausler/code/secret-project/venv/lib/python2.7/site-packages/django/db/models/manager.py", line 163, in filter
    return self.get_queryset().filter(*args, **kwargs)
  File "/Users/micahhausler/code/secret-project/venv/lib/python2.7/site-packages/django/db/models/query.py", line 593, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "/Users/micahhausler/code/secret-project/venv/lib/python2.7/site-packages/django/db/models/query.py", line 611, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "/Users/micahhausler/code/secret-project/venv/lib/python2.7/site-packages/django/db/models/sql/query.py", line 1204, in add_q
    clause = self._add_q(where_part, used_aliases)
  File "/Users/micahhausler/code/secret-project/venv/lib/python2.7/site-packages/django/db/models/sql/query.py", line 1240, in _add_q
    current_negated=current_negated)
  File "/Users/micahhausler/code/secret-project/venv/lib/python2.7/site-packages/django/db/models/sql/query.py", line 1131, in build_filter
    clause.add(constraint, AND)
  File "/Users/micahhausler/code/secret-project/venv/lib/python2.7/site-packages/django/utils/tree.py", line 104, in add
    data = self._prepare_data(data)
  File "/Users/micahhausler/code/secret-project/venv/lib/python2.7/site-packages/django/db/models/sql/where.py", line 79, in _prepare_data
    value = obj.prepare(lookup_type, value)
  File "/Users/micahhausler/code/secret-project/venv/lib/python2.7/site-packages/django/db/models/sql/where.py", line 352, in prepare
    return self.field.get_prep_lookup(lookup_type, value)
  File "/Users/micahhausler/code/secret-project/venv/lib/python2.7/site-packages/netfields/fields.py", line 32, in get_prep_lookup
    return self.get_prep_value(value)
  File "/Users/micahhausler/code/secret-project/venv/lib/python2.7/site-packages/netfields/fields.py", line 41, in get_prep_value
    return unicode(self.to_python(value))
  File "/Users/micahhausler/code/secret-project/venv/lib/python2.7/site-packages/netfields/fields.py", line 21, in to_python
    return self.python_type()(value)
  File "/Users/micahhausler/code/secret-project/venv/lib/python2.7/site-packages/netaddr/ip/__init__.py", line 907, in __init__
    implicit_prefix, flags)
  File "/Users/micahhausler/code/secret-project/venv/lib/python2.7/site-packages/netaddr/ip/__init__.py", line 802, in parse_ip_network
    raise TypeError('unexpected type %s for addr arg' % type(addr))
TypeError: unexpected type <type 'list'> for addr arg
```

**Comment by micahhausler** [comment]
@jimfunk can we re-open this? I'm using 0.3.1 and this is breaking in the exact same way it did before

CC: @thinkt4nk

**Comment by jimfunk** [comment]
I'm about to do a new release so I'll see if I can replicate this.

**Comment by jimfunk** [comment]
I am unable to replicate this with the current code. Is there anything else going on in your app besides the above model?

**Comment by jimfunk** [comment]
Is this still an issue for you?
