### ISSUE TITLE
netfields is incompatible with Django 1.9: ImportError on "from django.db.models.lookups import default_lookups"

### ISSUE THREAD

**Issue by spiow** [jimfunk/django-postgresql-netfields#48]
From diff it seems that in Django 1.9, filling 'default_lookups' dictionary was replaced with Field.register_lookup(<lookup_class>).

Full trace:

Traceback (most recent call last):
  File "/opt/ep/project/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/opt/ep/env/3/lib/python3.4/site-packages/django/core/management/__init__.py", line 350, in execute_from_command_line
    utility.execute()
  File "/opt/ep/env/3/lib/python3.4/site-packages/django/core/management/__init__.py", line 324, in execute
    django.setup()
  File "/opt/ep/env/3/lib/python3.4/site-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/opt/ep/env/3/lib/python3.4/site-packages/django/apps/registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "/opt/ep/env/3/lib/python3.4/site-packages/django/apps/config.py", line 116, in create
    mod = import_module(mod_path)
  File "/opt/ep/env/3/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/opt/ep/env/3/lib/python3.4/site-packages/netfields/apps.py", line 3, in <module>
    from django.db.models.lookups import default_lookups
ImportError: cannot import name 'default_lookups'

**Comment by jimfunk** [comment]
I just released 0.5.2, which should support Django 1.9 now
