### ISSUE TITLE
Problem with ArrayField and ModelSerializer

### ISSUE THREAD

**Issue by virusdefender** [jimfunk/django-postgresql-netfields#84]
There are some demo code

https://github.com/virusdefender/django-postgresql-netfields/commit/cf21f8fdd351f19ada3d10a3d574921055170367

I added three tests, but the last two tests will fail

https://travis-ci.org/virusdefender/django-postgresql-netfields/jobs/470819231

```
======================================================================
ERROR: test_serialize_inet_array (test.tests.test_rest_framework_fields.FieldsTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/virusdefender/django-postgresql-netfields/test/tests/test_rest_framework_fields.py", line 83, in test_serialize_inet_array
    self.assertEqual(TestSerializer(instance).data, {"field": ["1.2.3.0/24"]})
  File "/home/travis/build/virusdefender/django-postgresql-netfields/.tox/py36-django18/lib/python3.6/site-packages/rest_framework/serializers.py", line 534, in data
    ret = super(Serializer, self).data
  File "/home/travis/build/virusdefender/django-postgresql-netfields/.tox/py36-django18/lib/python3.6/site-packages/rest_framework/serializers.py", line 263, in data
    self._data = self.to_representation(self.instance)
  File "/home/travis/build/virusdefender/django-postgresql-netfields/.tox/py36-django18/lib/python3.6/site-packages/rest_framework/serializers.py", line 501, in to_representation
    ret[field.field_name] = field.to_representation(attribute)
  File "/home/travis/build/virusdefender/django-postgresql-netfields/.tox/py36-django18/lib/python3.6/site-packages/rest_framework/fields.py", line 1574, in to_representation
    return [self.child.to_representation(item) if item is not None else None for item in data]
  File "/home/travis/build/virusdefender/django-postgresql-netfields/.tox/py36-django18/lib/python3.6/site-packages/rest_framework/fields.py", line 1574, in <listcomp>
    return [self.child.to_representation(item) if item is not None else None for item in data]
  File "/home/travis/build/virusdefender/django-postgresql-netfields/.tox/py36-django18/lib/python3.6/site-packages/rest_framework/fields.py", line 1791, in to_representation
    value = value_from_object(self.model_field, obj)
  File "/home/travis/build/virusdefender/django-postgresql-netfields/.tox/py36-django18/lib/python3.6/site-packages/rest_framework/compat.py", line 150, in value_from_object
    return field._get_val_from_obj(obj)
  File "/home/travis/build/virusdefender/django-postgresql-netfields/.tox/py36-django18/lib/python3.6/site-packages/django/db/models/fields/__init__.py", line 843, in _get_val_from_obj
    return getattr(obj, self.attname)
AttributeError: 'str' object has no attribute 'field'
======================================================================
```

**Comment by jimfunk** [comment]
This is a bug in Django 1.8: https://code.djangoproject.com/ticket/25143

It's mentioned in our CHANGELOG, but I guess I should mention it in the README.

Unfortunately, there is no way to work around it in this project. The only way to make it work is to upgrade to at least Django 1.9.6 or apply a patch to your Django version.

**Comment by virusdefender** [comment]
It also occurs in Django 2.0

https://travis-ci.org/virusdefender/django-postgresql-netfields/jobs/470819229

**Comment by jimfunk** [comment]
OK. I see what's going on. This is something different, but again, not a bug in this project.

You are creating Django REST Framework serializers, but letting Django REST Framework detect the field type. However, Django REST Framework does not know how to deal with custom fields that are not present in core Django such as these, nor should it.

That's why this package contains Django REST Framework compatible fields under netfields/rest_framework.py. To use them you need to explicitly define them, which is a good practice anyway. See test/tests/test_rest_framework_fields.py for some examples.

**Comment by virusdefender** [comment]
OK, thanks a lot~
